app/urls.py
from django.urls import path;
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings

urlpatterns = [
    path('', views.index, name="home"),
    path('signup/', views.signup_view, name='signup'),
    path('donate/', views.donate_view, name='donate'),
    path('plant/', views.plant_view, name='plant'),
    path('profile/', views.profile_view, name='profile'),
    path('why_trees/', views.why_trees_view, name="why-trees"),
    path('store_locator/', views.store_locator_view, name="store-locator"),
    path('merchandise', views.merchandise_view, name="merchandise"),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout')
]

aranyani_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    planter = models.BooleanField(default=False)
    donator = models.BooleanField(default=False)
    point = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class Donation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(decimal_places=4, max_digits=50)
    city = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}, {}'.format(self.user.username, self.amount)

class Plantation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}, {}'.format(self.user.username, self.city)

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    planter = forms.BooleanField(required=False)
    donator = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'planter', 'donator', 'password1', 'password2')

class LoginForm(forms.Form):
    username = forms.CharField(max_length=128, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    password = forms.CharField(max_length=128, widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

class PlantForm(forms.Form):
    city = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'city-name'}))

class DonateForm(forms.Form):
    city = forms.CharField(max_length=128, widget=forms.TextInput(attrs={'class': 'form-control', 'id': 'city-name'}))
    amount = forms.DecimalField(max_value=10000, decimal_places=2)

app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import login, authenticate
from .forms import SignUpForm, DonateForm, PlantForm, LoginForm
from .models import Donation, Plantation
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
import stripe
import math

stripe.api_key = "sk_test_51HsaCRHFGa5Kppu9rEbW27J3whw1Qm3rKUCuFW0CwtYeTqAgpvaR4J7YKG3KaCBwHIkV6hyQDACXjmfcVbHmBLTv00hbI6xWwK"

def index(request):
    return render(request, 'app/home.html')

def signup_view(request):
    form = SignUpForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        user.refresh_from_db()
        user.profile.planter = form.cleaned_data.get('planter')
        user.profile.donator = form.cleaned_data.get('donator')
        user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('home')
    
    return render(request, 'registration/signUp.html', {'form': form})

def login_view(request):
    form = LoginForm(request.POST or None)
    redirect_to = request.GET.get('next', '')
    if request.POST:
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                nextPage = request.GET.get('next', '')
                return HttpResponseRedirect(nextPage)
            else:
                error = True
                return render(request, 'registration/login.html', {'form': form, 'error': error, 'redirect_to': redirect_to})
    return render(request, 'registration/login.html', {'form': form, 'redirect_to': redirect_to})

@login_required
def donate_view(request):
    form = DonateForm(request.POST or None)
    succeeded = False
    amount = 0
    city = None
    if request.POST:
        if form.is_valid():
            stripe_token = request.POST.get('stripeToken')
            amount = request.POST.get('amount')
            charge = stripe.Charge.create(
                amount= math.floor(float(amount)),
                currency= 'inr',
                description = "donation charge",
                source = stripe_token,
            )
            if charge:
                newDonation = Donation.objects.create(user=request.user, amount=amount, city=request.POST.get('city'))
                newDonation.save()
                request.user.profile.donator = True
                request.user.profile.point += 50
                request.user.profile.save()
                amount = form.cleaned_data['amount']
                city = form.cleaned_data['city']
                succeeded = True

    context = {
        'form': form,
        'amount': amount,
        'city': city,
        'succeeded': succeeded
    }
    return render(request, 'app/donate.html', context=context)

@login_required
def plant_view(request):
    form = PlantForm(request.POST or None)
    succeeded = False
    fromCity = None
    if request.POST:
        if form.is_valid():
            newPlantation = Plantation.objects.create(user=request.user, city=form.cleaned_data['city'])
            newPlantation.save()
            request.user.profile.planter = True
            request.user.profile.point += 50
            request.user.profile.save()
            fromCity = form.cleaned_data['city']
            succeeded = True

    context = {
        'form': form,
        'city': fromCity,
        'succeeded': succeeded
    }
    return render(request, 'app/plant.html', context=context)

@login_required
def profile_view(request):
    return render(request, 'app/profile.html')

def why_trees_view(request):
    return render(request, 'app/why_trees.html')

def store_locator_view(request):
    return render(request, 'app/store-locator.html')

def merchandise_view(request):
    point = request.user.profile.point
    return render(request, 'app/merchandise.html', {'point': point})

templates/app/donate.html
{% extends 'layout.html' %}
{% load static %}

{% block endscripts %}
    <script src="{% static 'js/map.js' %}"></script>
    <script src="{% static 'js/donate-cert.js' %}"></script>
    <script src="{% static 'js/donate-stripe.js' %}"></script>
{% endblock endscripts %}

{% block links %} 
<script src='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
<script src="https://js.stripe.com/v3/"></script>

{% endblock links %}

{% block content %}
<div class="container-fluid main-content">
    {% if not succeeded %}
        <div class="row max-height">
            <div class="col-md-5 scroll border-right">
                <div class="mapFunctionsSection">
                    <h2>Map Functions</h2>
                    <button id="locate-me-btn" class="btn btn-success">Locate me</button>
                    <button id="reset-btn" class="btn btn-warning">Reset</button> 
                </div>
                <hr />
                <div class="showMapDataSection">
                    <h2>Show Map Data</h2>
                    <div class="map-form-group">
                    <label for="deathRateShow" class="btn btn-danger no-pointer">Show death Rate</label>
                    <input type="checkbox" id="death-rate-checkbox">
                </div>
                <div class="map-form-group">
                    <label for="deathRateShow" class="btn btn-primary no-pointer">Show co2 emission Rate</label>
                    <input type="checkbox" id="c02-emission-rate-checkbox">
                </div>
                </div>
                <hr />
                <h2>Fill the donator's form</h2>
             
                <form method="POST" action="{% url 'donate' %}" id="payment-form">
                    {% csrf_token %}
                    <div class="form-group mt-4">
                        <label for="card-element">
                        Credit or debit card
                        </label>
    
                        <div id="card-element" class="mt-2">
                        <!-- A Stripe Element will be inserted here. -->
                        </div>                          
                    
                        <!-- Used to display Element errors. -->
                        <div id="card-errors" role="alert"></div>
                    </div>
                    <div class="form-group">
                        <label for="Amount">Amount</label>
                        {{form.amount}}
                    </div>
                    <div class="form-group">
                    <label for="city">City</label>
                    {{ form.city }}
                    <button id="map-area-btn" class="btn btn-secondary mt-2">Check Area On Map</button>
                    </div>
                <button type="submit" id="donate-submit-btn" class="btn btn-danger">Donate</button>
                </form>
            </div>
            <div class="col-md-7">
                <div class="map-container" style="cursor: grab;" id="mapContainer"></div>
            </div>
        </div>
        {% else %}
        <div class="center">
            <h2>You have donated successfully to sustain the world</h2>
            <canvas width="800px" height="600px" data-username="{{user.username}}" data-amount="{{amount}}" data-city="{{city}}" id="donate-cert-canvas"></canvas>
            {% endif %}
        </div>

</div>
<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch demo modal
  </button> -->
  
  <!-- Modal -->
  <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>    
  <div  id='aqi-map'  style='height:300px;'  />   -->

<!-- 
<link  rel="stylesheet"  href="http://cdn.leafletjs.com/leaflet-0.7.5/leaflet.css"  />  
<script  src="http://cdn.leafletjs.com/leaflet-0.7.5/leaflet.js"></script>  
  
<script>  
      var  OSM_URL  =  'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';  
      var  OSM_ATTRIB  =  '&copy;  <a  href="http://openstreetmap.org/copyright">OpenStreetMap</a>  contributors';  
      var  osmLayer  =  L.tileLayer(OSM_URL,  {attribution:  OSM_ATTRIB});  
  
      var  WAQI_URL    =  "https://tiles.waqi.info/tiles/usepa-aqi/{z}/{x}/{y}.png?token=454dae78cc9ce3183bc6e9bcc1eed6637df4556e";  
      var  WAQI_ATTR  =  'Air  Quality  Tiles  &copy;  <a  href="http://waqi.info">waqi.info</a>';  
      var  waqiLayer  =  L.tileLayer(WAQI_URL,  {attribution:  WAQI_ATTR, tileSize: 512, minZoom: 0});  
  
      var  aqiMap  =  L.map('aqi-map', {
          center: [-6.9273026, 27.9693414],
          zoom: 1.2
      }) 
      aqiMap.addLayer(osmLayer).addLayer(waqiLayer);  
</script>
   -->

{% endblock content %}

templates/app/merchandise.html
{% extends 'layout.html' %}
{% load static  %}

{% block content %}
<div class="merchandise-header">
        <h1>Get Your Gifts</h1>
        <p>Plant and Donate more for more gifts</p>
    </div>


    <div class="container" style="margin-top: 80px; position: relative;">
        <div class="text-center mb-5">
            <h2>Shop With Points</h2>
        </div>
        <div class="row mt-5" style="justify-content: space-evenly">
            <div class="card col-md-3 shop-item-card">
                <img src="{% static 'assets/bracelet.jpg' %}" width="100%" height="50%" alt="bracelet" class="card-img-top shop-card-item-img">
                <div class="card-body">
                    <h3 class="card-title">Bracelet</h3>
                    <p>250 points</p>
                    <button class="btn btn-danger">Get</button>
                </div>
            </div>
            <div class="card col-md-3 shop-item-card">
                <img src="{% static 'assets/bracelet.jpg' %}" width="100%" height="50%" alt="bracelet" class="card-img-top shop-card-item-img">
                <div class="card-body">
                    <h3 class="card-title">Bracelet</h3>
                    <p>250 points</p>
                    <button class="btn btn-danger">Get</button>
                </div>
            </div>
            <div class="card col-md-3 shop-item-card">
                <img src="{% static 'assets/bracelet.jpg' %}" width="100%" height="50%" alt="bracelet" class="card-img-top shop-card-item-img">
                <div class="card-body">
                    <h3 class="card-title">Bracelet</h3>
                    <p>250 points</p>
                    <button class="btn btn-danger">Get</button>
                </div>
            </div>
            <div class="card col-md-3 shop-item-card">
                <img src="{% static 'assets/tshirt.jpg' %}" width="100%" height="50%" alt="bracelet" class="card-img-top shop-card-item-img">
                <div class="card-body">
                    <h3 class="card-title">Tshirt</h3>
                    <p>500 points</p>
                    <button class="btn btn-danger">Get</button>
                </div>
            </div>
            <div class="card col-md-3 shop-item-card">
                <img src="{% static 'assets/tshirt.jpg' %}" width="100%" height="50%" alt="bracelet" class="card-img-top shop-card-item-img">
                <div class="card-body">
                    <h3 class="card-title">Tshirt</h3>
                    <p>500 points</p>
                    <button class="btn btn-danger">Get</button>
                </div>
            </div>
            <div class="card col-md-3 shop-item-card">
                <img src="{% static 'assets/tshirt.jpg' %}" width="100%" height="50%" alt="bracelet" class="card-img-top shop-card-item-img">
                <div class="card-body">
                    <h3 class="card-title">Tshirt</h3>
                    <p>500 points</p>
                    <button class="btn btn-danger">Get</button>
                </div>
            </div>
        </div>
    </div>

  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4" style="display: flex; flex-direction: column; align-items: center; justify-content: center;">
         <img src="{% static '/assets/Aranyani_logo.png' %}" width="100px" height="100px" alt="aranyani logo"> 
         <h2>Aranyani</h2>
         </div>
        <div class="footer-links mt-4 col-md-4">
          <h2>Quick Links</h2>
          <ul>
            <li><a href="#dataSection" data-scroll-to="#dataSection" class="footer-btn">data</a></li>
            <li><a href="#graphSection" data-scroll-to="#graphSection">graph</a></li>
            <li><a href="#impactSection" data-scroll-to="#impactSection">impact</a></li>
            <li><a href="#teamSection" data-scroll-to="#teamSection">team</a></li>
            <li><a href="#howSection" data-scroll-to="#howSection">how we work</a></li>
          </ul>
        </div>
        <div class="col-md-4 mt-4">
          <h2>Contact Us</h2>
          <div style="position: relative;">
            <i class="fa fa-phone-square" style="font-size: 40px;" aria-hidden="true"></i>
            <span style="position: absolute; top: 30%; margin-left:10px">+91-8429845032</span>
          </div>
        </div>
        </div>
      </div>
      <div style="display: grid; place-items: center;">
        <h6>© Copyright Aranyani</h6>
      </div>
    </div>
  </div>
{% endblock content %}

templates/app/plant.html
{% extends 'layout.html' %}
{% load static %}
{% block endscripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.3.0/papaparse.min.js" integrity="sha512-rKFvwjvE4liWPlFnvH4ZhRDfNZ9FOpdkD/BU5gAIA3VS3vOQrQ5BjKgbO3kxebKhHdHcNUHLqxQYSoxee9UwgA==" crossorigin="anonymous"></script>
<script src="{% static 'js/map.js' %}"></script>
<script src="{% static 'js/planted-cert.js' %}"></script>
{% endblock endscripts %}

{% block links %} 


<script src='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />
 
{% endblock links %}

{% block content %}
<div class="container-fluid main-content">
    {% if not succeeded %}
    <div class="row max-height">
        <div class="col-md-5 scroll border-right">
            <div class="mapFunctionsSection">
                <h2>Map Functions</h2>
                <button id="locate-me-btn" class="btn btn-success">Locate me</button>
                <button id="reset-btn" class="btn btn-warning">Reset</button>
            </div>
            <hr />
            <div class="showMapDataSection">
                <h2>Show Map Data</h2>
                 <div class="map-form-group">
                    <label for="deathRateShow" class="btn btn-danger no-pointer">Show death Rate</label>
                    <input type="checkbox" id="death-rate-checkbox">
                </div>
                <div class="map-form-group">
                    <label for="deathRateShow" class="btn btn-primary no-pointer">Show co2 emission Rate</label>
                    <input type="checkbox" id="c02-emission-rate-checkbox">
                </div>

            </div>
            <hr />
                <h2>Fill the Planter's form</h2>
                <form method="POST" action="{% url 'plant' %}">
                    {% csrf_token %}
                    <div class="form-group">
                    <label for="city">City</label>
                    {{ form.city }}
                    <button id="map-area-btn" class="btn btn-secondary mt-2">Check Area On Map</button>
                    </div>
                    <button type="submit" class="btn btn-success">Plant</button>
                </form>
                <hr />
        </div>
                <div class="col-md-7">
                    <div class="map-container" style="cursor: grab;" id="mapContainer"></div>    
                </div>
        </div>
        {% else %}
        <div class="center">
            <h2>You have volunteered to help plant to make the planet a better place</h2>
            <canvas width="800px" height="600px" data-username="{{user.username}}" data-city="{{city}}" id="planted-cert-canvas"></canvas>
        </div>
    {% endif %}
    
</div>
{% endblock content %}

templates/app/profile.html
{% extends 'layout.html' %}

{% block content %}
<div class="card profile-card container main-content" style="width: 100%">
    <div class="card-body" style="position: relative;">
      <h3 class="card-title">Your Profile</h3>
      <a class="btn btn-secondary" href="{% url 'logout' %}" style="position: absolute; right: 0; top: 0;">Logout</a>
      <h5>Username: <span class="profile-info-name">{{user.username}}</span></h2>
        <h5>Email: <span class="profile-info-name">{{user.email}}</span></h5>
        {% if user.profile.donator %}
            <h5>You are a donator, here is you donation details</h5>
            {% for donation in user.donation_set.all %}
                <ul>
                    <li>You made {{donation.amount}}$ from {{donation.city}} on {{donation.created_at}}</li>
                </ul>
            {% endfor %}
            <hr />
        {% endif %}
        {% if user.profile.planter %}
            <h5>You are a Planter, here is you plantation details</h5>
            {% for plantation in user.plantation_set.all %}
                <ul>
                    <li>You made a request to plant at {{plantation.city}} on {{plantation.created_at}}</li>
                </ul>
            {% endfor %}
        {% endif %}
    </div>
  </div>
    </div>
{% endblock content %}

templates/app/store-locator.html
{% extends 'layout.html' %}
{% load static %}

{% block links %} 
<script src='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />

{% endblock links %}

{% block endscripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.3.0/papaparse.min.js" integrity="sha512-rKFvwjvE4liWPlFnvH4ZhRDfNZ9FOpdkD/BU5gAIA3VS3vOQrQ5BjKgbO3kxebKhHdHcNUHLqxQYSoxee9UwgA==" crossorigin="anonymous"></script>
    <script src="{% static 'js/store-locator.js' %}"></script>
{% endblock endscripts %}
{% block content %}
<div class="container-fluid store-locator-container row" style="margin-top: 80px; overflow: hidden;">
    <div class="sidebar-search col-md-4" style="overflow-y: scroll; height: 100%;">
        <h3 style="color: #333">Wood Store Locator</h3>
        <input type="text" id="locator-search" class="locator-search" placeholder="search">
        <button id="reset" class="btn btn-secondary">reset</button>
        <ul class="list-group" id="store-list">
        </ul>
    </div>
    <div class="col-md-8" id="storeMapContainer"></div>
</div>
{% endblock content %}

templates/app/why_trees.html
{% extends 'layout.html' %}
{% load static %}
{% block endscripts %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock endscripts %}
{% block content %}
    <div class="why-trees-header">
        <h2 data-aos="zoom-in">Why Trees</h2>
    </div>
    <div class="container">
        <div class="whySection">
            <h2 class="text-center mt-5 mb-5" data-aos="fade-in" data-aos-duration="300">REASONS WHY WE NEED TO PLANT TRESS</h2>
            <div class="whySection__point">
                <div class="row mb-5" style="justify-content: center; align-items: center;">
                    <img width="300px" data-aos="flip-up" data-aos-delay="600" data-aos-duration="300" height="300px" src="{% static 'assets/Mango_Tree_SriLanka.jpg' %}" alt="" class="col-md-4">
                    <div class="col-md-7" data-aos="fade-left" data-aos-delay="900">
                        <h2 class="mt-2 mb-3">FOOD SECURITY</h2>
                        <p>For every tree we plant, it will provide 700 rupees worth of food and nutrition annually (true cost of a meal being 13 rupees). A dead tree would result in an output of 50000 rupees, while a living tree would have an all-in-all net outcome of 23 lakh rupees in total, both over a period of about 50 years.</p>
                    </div>
                </div>
              </div>
                <hr class="bg-dark" />
            <div class="whySection__point">
                <div class="row mb-5" style="flex-direction: row-reverse; justify-content: center; align-items: center;">
                    <img width="300px" height="300px" src="{% static 'assets/Forest-bathing.jpg' %}" data-aos="flip-down" data-aos-duration="300" alt="" class="col-md-4">
                    <div class="col-md-7" data-aos="fade-right" data-aos-delay="300">
                        <h2 class="mt-5 mb-3">PREVENT DEFORESTATION</h2>
                        <p>According to studies, 40% of India's natural forest cover has been lost in the last 95 years, major factors being mining, agriculture, fishery, and urbanization. The adverse effect of this major loss can be reversed by reforestation, improving the lives of an estimate of 275 million Indians that are dependent..</p>
                    </div>
                </div>
              </div>
                <hr class="bg-dark" />
            <div class="whySection__point">
                <div class="row mb-5" style="justify-content: center; align-items: center;">
                    <img width="300px" height="300px" src="{% static 'assets/nature.jpg' %}" alt="" data-aos="flip-down" data-aos-duration="300" style="border-radius: 70%;" class="col-md-4">
                    <div class="col-md-7" data-aos="fade-left" data-aos-delay="300">
                        <h2 class="mt-5 mb-3">ADAPT TO CLIMATE CHANGE</h2>
                        <p>A fully-grown tree encompasses  about upto 48 pounds of carbon annually. Given India's poor Air Quality Index scores, this will be a huge step forward in tackling air pollution. Problems like untimely rains and record setting increasing or decreasing temperature will also be tackled, taking climate change into account.</p>
                    </div>
                </div>
              </div>
                <hr class="bg-dark" />
          </div>
    </div>
{% endblock content %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{% static '/assets/favicon.png' %}" sizes="16x16" type="image/png">
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
    />
  <link rel="stylesheet" href="{% static 'css/Chart.min.css' %}">
  <script src="{% static 'js/Chart.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    {% block links %}
    {% endblock links %}
    <title>Aranyani</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md fixed-top navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Aranyani</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'why-trees' %}">Why Trees</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'store-locator' %}">Wood Store Locator</a>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'merchandise' %}">Merchandise</a>
            </li>
            <li class="nav-item">
              <a class="nav-link donate-link" href="{% url 'donate' %}"
                >Donate
                <span><i class="fa fa-heart" aria-hidden="true"></i></span
              ></a>
            </li>
            <li class="nav-item">
              <a class="nav-link plant-link" href="{% url 'plant' %}"
                >Plant <span><i class="fa fa-tree" aria-hidden="true"></i></span
              ></a>
            </li>
            {% if user.is_authenticated %}
              <li class="nav-item ml-2">
                <a href="{% url 'profile' %}" class="nav-link bg-link">
                  {{user.username}}
                  <span>
                    |
                    {{user.profile.point}}pts
                  </span>
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock content %}
    <script>
      var globalFiles = {
        "globalConcFile": "{% static '/data/global-concentration.json' %}",
        "co2File": "{% static '/data/co2.geojson' %}",
        "deathRateFile": "{% static '/data/death-rates-total-air-pollution.geojson' %}",
        "woodstoresFile": "{% static '/data/woodstore-locations.csv' %}",
        "logo": "{% static '/assets/Aranyani_logo_50_x_50.png' %}"
      }
    </script>
   <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script> 
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
      integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
      crossorigin="anonymous"
    ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>
    {% block endscripts %}
    {% endblock endscripts %}
</body>
</html>